### ISSUE TITLE
Supervision::Behaviors, and ::Configuration elements.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-supervision#12]
This celluloid/celluloid#511 refactor process has been a bit involved over the last few days. I've refactored twice so far, only pushed pieces of it, and I am going for a third and final refactor. A lot changed, but it was mostly theoretical, trying to correct the design. I'll just skip to the end result design.

I'm posting this for advanced warning, feedback, etc. Please tread carefully as I'm trying to clarify a pretty complex aspect of the system. It's sort of an `ActorSystem` superstructural layer, and yet similar to `Call` and `Proxy` in how far-reaching and potentially convoluted if not done right the first time. On that note, I am going to do the new way first, then backport. I was backporting simultaneously, and I that was pure insanity. I will keep the existing tests unchanged, and add tests for the new areas. And I will populate the depreciation sections with the monkey patches needed to keep things going in `0.16.0` ... and from what I've seen, monkey patched or not, it still a lot faster and stronger.

> Here are the key elements I am going to build tests for, then flesh out. If one is using this in `backported` mode, none of this will be exposed. The standard behaviors reveal none of the complexity, but benefit from the greater efficiency, flexibility, and robustness:

### `Configuration` object ( #8 ) parameters.

0. `:type` [ required ] : the class of Actor. More in `Container` on this one.
0. `:as` [ optional ] : the `registry` stored name of the `Actor`.
0. `:args` [ optional ] : an array of arguments to send the `Actor`(s) at initialization.
0. `:block` [ optional ] : a block passed all the way into `Actor` initializations.
0. `:injections` [ special, plugin layer ] : More in `Injections` and `Behavior`
0. `:method` [ special, plugin layer ] : More on this in `Behavior` objects.
0. `:size`  [ plugin ] : More on this in `Behavior` objects: `Pool`.
0. `:routers` [ plugin ] : More on this in `Behavior` objects: `Coordinator`.
0. `:supervise` [ special, plugin layer ] : More on this In `Behavior` objects: `Tree`.
0. `:registry` [ optional ] : override the default registry ( `Services::Public` )

> #### Aliases:
> `:name => :as`
> `:kind => :type`
> `:pool => size`

---

> #### `:class` cannot be used as a parameter.
> Each parameter is also a method of `Instance` and `Configuration` objects.
> `class` is a keyword, so it cannot be used as a `method`. The `Configuration` parameter methods point to the specific `Instance` being configured at that moment. I'm particularly excited to show how easy and powerful it is to have `Actors` build their own `Instances`, `Containers`, `Trees`, etc.

### Foundational objects:

* `Container` a module, which if included turns the object into a foundry of sorts.
    * Right now that's two objects who can spawn supervised `Actor`(s):
        * `Configuration`
        * `Group` ( this one is going away, with legacy protection...
           because `Group` is both too vague and inaccurate,
           as it could be supervising one `Actor` only,
           or be an entire `Pool` or `Coordinator`.
    * This is where the repeated refactoring came in.
    * `Container` will become a class. More in `Behaviors`...
* `Configuration` which wraps `Instances` and keeps them ordered.
    * Mostly class methods, and a collection of ordered `Instances` kept static.
    * Can be reused, sent between scopes, etc. It is not an `Actor`. It is blueprints.
* `Instances` are the point of `Configuration` just as `Member`(s) are the point of `Containers`.

### `Injections` create plugins.

Right now we have `PoolManager` living on by passing a `Hash` of `:injections` into `Member` who offers special handling, by special classes insertion points at certain points in the flow of the `Member` lifecycle:

* `:before_initialization` : *New* injection allows for a complete plugin system.
* `:after_initialization` : Previous way of turning a `Pool` into a supervisor.
* `:before_start`: Also pre-existing injection used by `Pool`.
* `:before_restart`: Unused, left there for the future during the `Pool` refactor.

### `Behaviors` bring in `Injections` and mix-in plugin classes.

Using `Pool` ( no longer `PoolManager` except in `backported` mode ) as the model, there will also be a completion of `Coordinator` and the transformation of `Group` into `Tree` -- with the essential pieces from `Group` staying in `Container` and being provided to all `Behavior` objects, as well as being itself in abstract form ( for a la carte `Supervisors` and the generic `Group` of supervised `Actors` )

Using `Injections` then, the catching parameters as flags, certain `Behaviors` can be called the old way -- `Actor.pool` or `PoolManagerDescendent.new` -- but are much more easily instantiated by just using a parameter with implications. For example `:size` ( or it's "on the nose" alias `:pool` ) would be caught by `:before_initialization` high-performance classifier, and turned into a `Supervision::Behavior::Pool` ... same for `:routers` and `Supervision::Behavior::Coordinator` and `:supervises` becoming `Supervision::Behavior::Tree`.

---

All of this is being done with #11 in mind, which is a lot easier than it sounds, if supervision trees are back, and/or there's a `:root` supervisor again. That right there changes almost everything.

---

### `Supervision::Services` and the return of the `Tree`

Now, there are two supervisors spawned by default, which is actually exactly as many as before, by default; except one is supervising the other, and one is the `general population` supervisor.

These are part of the `Supervision::Services::Root` supervision `Container` ( was `Group` ); in order of instantiation:

* `:notification_fanout` ...is `Celluloid::Notifications::Fanout`
* `:default_incident_reporter` ...is `Celluloid::IncidentReporter`
* `:group_manager` ...is `Group::Manager` ( part of why `Supervision::Group` became `Supervision::Container` also... less ambiguity going forward )
* `:public_services` ...is `Supervision::Services::Public` ...
    * This one is not supervising anything at start. It could even be `run!` at first use, but all the `one-off` unspecifically instantiated `Actor` supervision happens here... all the unclaimed supervisors, rather than spawning an entire `Container` for each `Actor` ... if that behavior is desired, that can still be done, but it's no longer the default.
    * Reason being, it's caused radical increase of threads in use those instantiating many single `Actors` they don't particularly care about, but need to be supervised nonetheless.
    * Also, because supervisors have been dying and never returning ( #2 ).
* `:servers` ...[ future ] Once `Reel` and I'd imagine `celluloid-dns` adapt to the `celluloid-supervision` refactor.

This "trunk" and these "branches" are a primitive beginning for the new supervision `Tree` implementation, starting from one `Root` class, then expanding in multiple ordered layers.

---

As I endure the process of this gem and I beating the crap out of each other, the prospect of people enjoying building supervisors and those complex or simple supervisors always remaining stable, flexible, efficient, is pretty exciting. I don't expect this next refactor pass to be non-negotiable, but I'd like to get it down before getting into the minutia of how it all works. The code speaks for itself, and we can piece it apart that way. But for now, anything that jumps out at you: hit me with what strikes you.

**Comment by digitalextremist** [comment]
Done with this, need to document this though.

**Comment by ioquatix** [comment]
Should :default_incident_reporter just be :incident_reporter?

**Comment by ioquatix** [comment]
I'm not trying to bike shed :)

**Comment by digitalextremist** [comment]
No @ioquatix I appreciate the scrutiny. I've changed it to that, grepped all the libraries for use of that Symbol, and am testing with the changed ( better ) name.

**Comment by ioquatix** [comment]
Can you explain :servers in relation to rubydns

**Comment by digitalextremist** [comment]
@ioquatix now there are no "unsupervised supervisors" unless we explicitly decide to create a supervisor outside the root supervision tree.

This piece is fledgling/conceptional right now, but there are at least two "service containers" going all the time: the root supervisor, and the public services container, which is a child of the root supervisor. I'm talking about another child of the root, parallel to the public services ( which are generally a la carte supervised actors ) ... So if you instantiate `Reel` supervised, or `RubyDNS` for example, it would supervised by the `:servers` service.

If your server fails, the servers service restarts it -- not a one-off supervisor like now. And if the servers service fails, the root restarts that container. This addresses #2 but also brings in #9 -- but like I said it's still a work in progress.

There is no `:servers` service at the moment, that is vaporware until `0.17.5` in my mind... once I double-back to update `Reel` to run `celluloid/current` non-backported to `0.16.0` behavior.

**Comment by digitalextremist** [comment]
@ioquatix to automatically link-in to the `:servers` service, I'm thinking something like `server!` in the class definition below `include Celluloid` could do it.. just for example.

**Comment by digitalextremist** [comment]
And the `:servers` service would not exist until there were one or more servers present, and instantiated.

**Comment by ioquatix** [comment]
I like the idea of servers, except it might encourage people to depend on global state. Does it make sense for there to be shared global actors? I can see arguments both ways. What's so bad about instantiating your own supervised/linked DNS resolver and just using that directly? A global shared DNS resolver maximises the value of cached records - on the other hand, this might be a security problem (cache poisoning) or a contention issue..

A name like `server!` while simple and obvious, also might be too generic. Similar to how `Celluloid::Logger` breaks all existing code that expects `Logger` to be `::Logger` (that's since been fixed right? Moved to `Celluloid::Internals`?), `server!` might be too generic.. perhaps something with celluloid in the name, e.g. `supervised_celluloid_server!` or something a bit more specific?

Perhaps we need to discuss the idea of servers in more detail once `celluloid-dns` takes shape.

**Comment by tarcieri** [comment]
> Does it make sense for there to be shared global actors?

Erlang has them

**Comment by ioquatix** [comment]
Does that mean yes?

**Comment by tarcieri** [comment]
Works for them :stuck_out_tongue_winking_eye:

**Comment by ioquatix** [comment]
Is there any reason to NOT have a global DNS resolver?

**Comment by digitalextremist** [comment]
@ioquatix I think there's a misunderstanding, but I agree `supervised_service! :servers` would be better than `servers!`

The misunderstanding that might be happening, is that there's no real change other than increased supervision. We already had `shared global actors` a la `Celluloid::Actor[:registry_key]` unless I'm misreading you there, what is added is now we have a supervision tree again. When I get back later I will post a diagram and start diagramming things more.

**Comment by digitalextremist** [comment]
@ioquatix this is more what I was trying to say:

![supervision tree-239 4](https://cloud.githubusercontent.com/assets/21095/7404792/807c28fe-ee9d-11e4-9704-105fe74171fe.png)

**Comment by digitalextremist** [comment]
`.services` actors is where your `RubyDNS` actor would be supervised, unless you distinguished it as to be supervised by `.servers` ... and I'm just proposing two ways to do that:

* `Celluloid.servers.supervise as: :blah, type: Celluloid::DNS`
    * or `Celluloid::DNS.supervise as: :blah, branch: :servers`
* Adding `supervised_service! :servers` to the `Class

**Comment by ioquatix** [comment]
This looks awesome.

**Comment by digitalextremist** [comment]
Glad you think so! This functionality is "in" but not really properly documented, or demonstrated. I will remember to do that in `Reel` so you can port that over to `Celluloid::DNS`!
