### ISSUE TITLE
How to correctly exit a supervision container?

### ISSUE THREAD

**Issue by ccoenen** [celluloid/celluloid-supervision#29]
I am currently converting a Celluloid 0.16 Application to 0.17, adding a gew niceties along the way.

This is a skeleton of what i'm doing:

```ruby
class Overlord < Celluloid::Supervision::Container
  supervise type: MyActor1, as: :some_name
  supervise type: MyActor1, as: :another_name
end

trap("INT") {
  Thread.new do
    Celluloid.logger.info "** Interrupt Received, Terminating"
    Celluloid::Notifications.publish "shutdown"
    # ???? What do I do?  <-----------------
  end
}

Overlord.run
```

Up until now, i just used `exit`, as there was no real reason not to do so. We'd like to extend the Script to wait for a clean shutdown of the two supervised actors, instead. I tried things like `Overlord.shutdown` or `Celluloid.register_shutdown` and whatever I could find that suggested a controlled stop of celluloid.

What is the _intended_ way to enc something like this?

**Comment by tarcieri** [comment]
I think the functionality to store a root actor was removed at one point, sorry :cry:

You can try something like this:

`Overlord.supervise_as :overlord`

and in the trap("INT") block:

`Celluloid::Actor[:overlord].shutdown`

**Comment by ccoenen** [comment]
Not a problem, I'm just looking for a way that works. I'll try your suggestion as soon as possible. I'll close this as it's not really an issue with celluloid/celluloid-supervision.

Thank you for the quick answer!

**Comment by digitalextremist** [comment]
Actually, there is a root actor brought back, and a tree of supervision containers that's only lightly used right now. But what @tarcieri still applies. `Celluloid` handles its own shutdown, but not in the sense it seems like you need. If you need support on this, definitely jump on our Google Group or ask a question with our StackOverflow tag.
