### ISSUE TITLE
supervisors_and_registry.rb not working correctly

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-supervision#3]
Migration of: celluloid/celluloid#430

**Comment by digitalextremist** [comment]
@ioquatix, @sb8244 this is not a race condition. Insert a `sleep` for as long as you like and it still won't restart. It's that `.actors` is not being updated. Resolving

**Comment by digitalextremist** [comment]
Actually, yes this is a race condition. But still it shouldn't be happening.

**Comment by ioquatix** [comment]
@digitalextremist thanks.
