### ISSUE TITLE
undefined method `services' for Celluloid:Module 

### ISSUE THREAD

**Issue by bogdanRada** [celluloid/celluloid-supervision#32]
Hello, 
  I had in the past the same issue for version 0.17 (can be seen here: https://github.com/celluloid/celluloid-pool/issues/10 ) and i was able to resolve this by doing this 

```ruby
  require 'celluloid/current'
```

However with version 0.18.0.pre, in order to resolve this issue, i have to do this:

```ruby
  require 'celluloid/current'
  celluloid_running = Celluloid.running? rescue false
  Celluloid.boot unless celluloid_running
  require 'celluloid'
```

 Is there a cleaner way of resolving this ?
Currently my code is this: 

```ruby
class TestActor
  include Celluloid
 include Celluloid::IO
 include Celluloid::Internals::Logger
end
TestActor.supervise(as: :test_actor, args: [])
```

What am i doing wrong? Or maybe now i have to require some other file from celluloid instead of "celluloid/current" ? 

If i don't put the last two lines and i only require "celluloid/current" i get this error: 

```ruby
/home/raul/.rvm/gems/ruby-2.3.3@celluloid_pubsub/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/deprecate/supervise.rb:54:in `router': undefined method `services' for Celluloid:Module (NoMethodError)
Did you mean?  supervise
	from /home/raul/.rvm/gems/ruby-2.3.3@celluloid_pubsub/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/deprecate/supervise.rb:6:in `supervise'
	from /home/raul/.rvm/gems/ruby-2.3.3@celluloid_pubsub/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/deprecate/supervise.rb:19:in `supervise'

```

**Comment by tarcieri** [comment]
This looks like a regression. Can you try `require 'celluloid/autostart'` instead of `require 'celluloid/current'`?

**Comment by bogdanRada** [comment]
That was my first attempt, however that fails too, because of error ```  Celluloid is not yet started; use Celluloid.boot ```. but if i do this: 

```
celluloid_running = Celluloid.running? rescue false
  Celluloid.boot unless celluloid_running
  require 'celluloid/autostart'
```

it works. However on older versions i didn't had to manually boot celluloid actor system .

**Comment by tarcieri** [comment]
This is definitely a bug. Thanks for reporting it. I will try to get it corrected this weekend and put out another 0.18 prerelease.

**Comment by bogdanRada** [comment]
Thanks :)

**Comment by bogdanRada** [comment]
this can be closed as it seems to be working with the new version. Thank you very much.
